Add faces for dired+
sellout/emacs-color-theme-solarized pull request #193
Opened 2016-12-07 01:42 UTC by ytaka

I added faces for dired+.
Could you merge this patch?

2016-12-08 17:33 UTC, periklis commented
Great work, thx. Missed that faces long time now

2023-02-09 08:53 UTC, sellout requested changes
There are definitely good additions here. Sorry it has taken so long, but if you update the PR, I promise to handle it quickly.

2023-02-09 08:53 UTC, sellout commented on solarized-definitions.el
> +                (helm-buffer-directory (:inherit helm-ff-directory))
I’d be happy to take the changes from here down, if you want to update the PR.

2023-02-09 08:53 UTC, sellout commented on solarized-definitions.el
> +             (cl-rotatef base01 base00 base0 base1 base2 base3)
Current version no longer uses `rotatef`.

2023-02-09 08:53 UTC, sellout commented on solarized-definitions.el
> +                (region (:background base02 :foreground nil :inverse-video nil))
This comes directly from the Vim theme, so I’m not likely to change it. But soon I’ll merge something like #191 which would make it easy to define variations like this locally (while still being able to refer to `base02`, etc.).

2026-03-07 01:57 UTC, closed without merging